---
title: "Australian Salaries"
subtitle: "TidyTuesday April 24, 2018 (Week 4)"
author: Neal S. Grantham `@nsgrantham`
output: html_notebook
---

```{r, message=FALSE}
library(tidyverse)
salary <- read_csv("../data/week4_australian_salary.csv")
salary <- salary %>%
  select(-one_of("X1", "gender_rank")) %>%
  separate(occupation, into = "occupation", sep = ";", extra = "drop")
```

```{r}
income <- salary %>%
  select(-individuals) %>%
  spread(gender, average_taxable_income) %>%
  rename(m_income = Male, f_income = Female)

ratio_breaks <- c(0, 0.5, 0.9, 10/9, 2, Inf)
ratio_labels <- c("Women outnumber men (2:1)", 
                  "Women outnumber men (10:9)", 
                  "Approximately equal", 
                  "Men outnumber women (10:9)", 
                  "Men outnumber women (2:1)")
workforce <- salary %>%
  select(-average_taxable_income) %>%
  spread(gender, individuals, fill=0) %>%
  rename(m_workforce = Male, f_workforce = Female) %>% 
  filter(m_workforce + f_workforce > 1000) %>%
  transform(mf_workforce_ratio = m_workforce / f_workforce) %>%
  transform(mf_workforce_category = cut(mf_workforce_ratio, breaks = ratio_breaks, 
                                        labels = ratio_labels, right = FALSE))
salary <- workforce %>% 
  left_join(income, by = "occupation")
```